<?php

declare(strict_types=1);

// Keep the normal edit training card in one place without changing form behavior.
?>
<div class="rf-card"><div class="rf-title">訓練状況</div><?php if (($errors['training_content'] ?? '') !== ''): ?><p class="err rf-section-err" role="alert"><?= $h($errors['training_content']) ?></p><?php endif; ?><div class="rf-body rf-body--compact">
	<div class="rf-row-3">
		<div class="rf-field rf-field-lg"><label class="rf-label" for="<?= $h($fieldId('training_am_1')) ?>">訓練内容 午前1</label><input id="<?= $h($fieldId('training_am_1')) ?>" type="text" name="training_am_1" value="<?= $h($form['training_am_1']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_am_1'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_am_1') !== '' ? ' aria-describedby="' . $h($describedBy('training_am_1')) . '"' : '' ?>><?php if (($errors['training_am_1'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_am_1')) ?>" role="alert"><?= $h($errors['training_am_1']) ?></p><?php endif; ?></div>
		<div class="rf-field rf-field-lg"><label class="rf-label" for="<?= $h($fieldId('training_am_2')) ?>"><?= $h($fieldLabel('training_am_2')) ?></label><input id="<?= $h($fieldId('training_am_2')) ?>" type="text" name="training_am_2" value="<?= $h($form['training_am_2']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_am_2'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_am_2') !== '' ? ' aria-describedby="' . $h($describedBy('training_am_2')) . '"' : '' ?>><?php if (($errors['training_am_2'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_am_2')) ?>" role="alert"><?= $h($errors['training_am_2']) ?></p><?php endif; ?></div>
		<div class="rf-field rf-field-lg"><label class="rf-label" for="<?= $h($fieldId('training_am_3')) ?>"><?= $h($fieldLabel('training_am_3')) ?></label><input id="<?= $h($fieldId('training_am_3')) ?>" type="text" name="training_am_3" value="<?= $h($form['training_am_3']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_am_3'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_am_3') !== '' ? ' aria-describedby="' . $h($describedBy('training_am_3')) . '"' : '' ?>><?php if (($errors['training_am_3'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_am_3')) ?>" role="alert"><?= $h($errors['training_am_3']) ?></p><?php endif; ?></div>
	</div>
	<div class="rf-row-3">
		<div class="rf-field rf-field-lg"><label class="rf-label" for="<?= $h($fieldId('training_pm_1')) ?>">訓練内容 午後1</label><input id="<?= $h($fieldId('training_pm_1')) ?>" type="text" name="training_pm_1" value="<?= $h($form['training_pm_1']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_pm_1'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_pm_1') !== '' ? ' aria-describedby="' . $h($describedBy('training_pm_1')) . '"' : '' ?>><?php if (($errors['training_pm_1'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_pm_1')) ?>" role="alert"><?= $h($errors['training_pm_1']) ?></p><?php endif; ?></div>
		<div class="rf-field rf-field-lg"><label class="rf-label" for="<?= $h($fieldId('training_pm_2')) ?>"><?= $h($fieldLabel('training_pm_2')) ?></label><input id="<?= $h($fieldId('training_pm_2')) ?>" type="text" name="training_pm_2" value="<?= $h($form['training_pm_2']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_pm_2'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_pm_2') !== '' ? ' aria-describedby="' . $h($describedBy('training_pm_2')) . '"' : '' ?>><?php if (($errors['training_pm_2'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_pm_2')) ?>" role="alert"><?= $h($errors['training_pm_2']) ?></p><?php endif; ?></div>
		<div class="rf-field rf-field-lg"><label class="rf-label" for="<?= $h($fieldId('training_pm_3')) ?>"><?= $h($fieldLabel('training_pm_3')) ?></label><input id="<?= $h($fieldId('training_pm_3')) ?>" type="text" name="training_pm_3" value="<?= $h($form['training_pm_3']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_pm_3'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_pm_3') !== '' ? ' aria-describedby="' . $h($describedBy('training_pm_3')) . '"' : '' ?>><?php if (($errors['training_pm_3'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_pm_3')) ?>" role="alert"><?= $h($errors['training_pm_3']) ?></p><?php endif; ?></div>
	</div>
	<div class="rf-break"></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('training_start_time')) ?>"><?= $h($fieldLabel('training_start_time')) ?></label><input id="<?= $h($fieldId('training_start_time')) ?>" type="time" name="training_start_time" value="<?= $h($form['training_start_time']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_start_time'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_start_time') !== '' ? ' aria-describedby="' . $h($describedBy('training_start_time')) . '"' : '' ?>><?php if (($errors['training_start_time'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_start_time')) ?>" role="alert"><?= $h($errors['training_start_time']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('training_end_time')) ?>"><?= $h($fieldLabel('training_end_time')) ?></label><input id="<?= $h($fieldId('training_end_time')) ?>" type="time" name="training_end_time" value="<?= $h($form['training_end_time']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['training_end_time'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('training_end_time') !== '' ? ' aria-describedby="' . $h($describedBy('training_end_time')) . '"' : '' ?>><?php if (($errors['training_end_time'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('training_end_time')) ?>" role="alert"><?= $h($errors['training_end_time']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-xs"><span class="rf-label"><?= $h($fieldLabel('training_time')) ?></span><div class="rf-value"><?= $h($form['training_time']) ?></div></div>
	<div class="rf-break"></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('lunch_time')) ?>"><?= $h($fieldLabel('lunch_time_minutes')) ?></label><input id="<?= $h($fieldId('lunch_time')) ?>" type="number" name="lunch_time" value="<?= $h($form['lunch_time']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['lunch_time'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('lunch_time') !== '' ? ' aria-describedby="' . $h($describedBy('lunch_time')) . '"' : '' ?>><?php if (($errors['lunch_time'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('lunch_time')) ?>" role="alert"><?= $h($errors['lunch_time']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('break_time')) ?>"><?= $h($fieldLabel('break_time_minutes')) ?></label><input id="<?= $h($fieldId('break_time')) ?>" type="number" name="break_time" value="<?= $h($form['break_time']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['break_time'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('break_time') !== '' ? ' aria-describedby="' . $h($describedBy('break_time')) . '"' : '' ?>><?php if (($errors['break_time'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('break_time')) ?>" role="alert"><?= $h($errors['break_time']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-xs"><span class="rf-label"><?= $h($fieldLabel('lunch_break_time_minutes')) ?></span><div class="rf-value"><?= $h($form['lunch_break_time']) ?>分</div></div>
	<div class="rf-field rf-field-xs"><span class="rf-label"><?= $h($fieldLabel('work_time_short')) ?></span><div class="rf-value"><?= $h($form['work_time']) ?></div></div>
</div></div>
