<?php

declare(strict_types=1);

// Keep the normal edit review card markup consistent with the confirm/detail wording.
?>
<div class="rf-card"><div class="rf-title">振り返り</div><div class="rf-body">
	<div class="rf-field rf-field-xl"><label class="rf-label" for="<?= $h($fieldId('rethink_am')) ?>"><?= $h($fieldLabel('rethink_am_short')) ?></label><input id="<?= $h($fieldId('rethink_am')) ?>" type="text" name="rethink_am" value="<?= $h($form['rethink_am']) ?>"<?= $readonly ? ' readonly' : '' ?>></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('achieve_am')) ?>"><?= $h($fieldLabel('achieve_short')) ?></label><input id="<?= $h($fieldId('achieve_am')) ?>" type="number" name="achieve_am" value="<?= $h($form['achieve_am']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['achieve_am'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('achieve_am') !== '' ? ' aria-describedby="' . $h($describedBy('achieve_am')) . '"' : '' ?>><?php if (($errors['achieve_am'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('achieve_am')) ?>" role="alert"><?= $h($errors['achieve_am']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('fatigue_am')) ?>"><?= $h($fieldLabel('fatigue_short')) ?></label><input id="<?= $h($fieldId('fatigue_am')) ?>" type="number" name="fatigue_am" value="<?= $h($form['fatigue_am']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['fatigue_am'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('fatigue_am') !== '' ? ' aria-describedby="' . $h($describedBy('fatigue_am')) . '"' : '' ?>><?php if (($errors['fatigue_am'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('fatigue_am')) ?>" role="alert"><?= $h($errors['fatigue_am']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-xl"><label class="rf-label" for="<?= $h($fieldId('rethink_pm')) ?>"><?= $h($fieldLabel('rethink_pm_short')) ?></label><input id="<?= $h($fieldId('rethink_pm')) ?>" type="text" name="rethink_pm" value="<?= $h($form['rethink_pm']) ?>"<?= $readonly ? ' readonly' : '' ?>></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('achieve_pm')) ?>"><?= $h($fieldLabel('achieve_short')) ?></label><input id="<?= $h($fieldId('achieve_pm')) ?>" type="number" name="achieve_pm" value="<?= $h($form['achieve_pm']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['achieve_pm'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('achieve_pm') !== '' ? ' aria-describedby="' . $h($describedBy('achieve_pm')) . '"' : '' ?>><?php if (($errors['achieve_pm'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('achieve_pm')) ?>" role="alert"><?= $h($errors['achieve_pm']) ?></p><?php endif; ?></div>
	<div class="rf-field rf-field-sm"><label class="rf-label" for="<?= $h($fieldId('fatigue_pm')) ?>"><?= $h($fieldLabel('fatigue_short')) ?></label><input id="<?= $h($fieldId('fatigue_pm')) ?>" type="number" name="fatigue_pm" value="<?= $h($form['fatigue_pm']) ?>"<?= $readonly ? ' readonly' : '' ?><?= ($errors['fatigue_pm'] ?? '') !== '' ? ' aria-invalid="true"' : '' ?><?= $describedBy('fatigue_pm') !== '' ? ' aria-describedby="' . $h($describedBy('fatigue_pm')) . '"' : '' ?>><?php if (($errors['fatigue_pm'] ?? '') !== ''): ?><p class="err" id="<?= $h($errorId('fatigue_pm')) ?>" role="alert"><?= $h($errors['fatigue_pm']) ?></p><?php endif; ?></div>
</div></div>
